### ISSUE TITLE
[BUG] Requests cannot be made: Error while processing item: 'tmdb_id'

### ISSUE THREAD

**Issue by daerup** [giuseppe99barchetta/SuggestArr#82]
Requests cannot be made: Error while processing item: 'tmdb_id' 

![image](https://github.com/user-attachments/assets/95ac231c-d730-4095-af61-fb1170504e9f)

Connections to plex and overseer can be made, although sometimes the metadata cannot be loaded:
`PlexClient - ERROR - Failed to retrieve metadata for item /library/metadata/94412: 200`
I think this happens primarley for a library using HamaTv agent even though this library is disabled in the configs.

Also I feel like the description of the different config options are not verbose enough. What exactly is the difference between `MAX_CONTENT_CHECKS`,  `MAX_SIMILAR_MOVIE `and `SEARCH_SIZE`? Which of these specify how many requests should be made?

**Comment by crispybegs** [comment]
i have the same issue.

**Comment by vahtos** [comment]
I can confirm this is also happening on the latest nightly. Though, this was working (made requests around 22 hours ago). I changed nothing and it stopped working. I am not using the HamaTv agent.

I tried editing config and retesting my API key for TMDB and it works. TMDB is also up right now. I suspect this might be on their end in some way.

**Comment by vahtos** [comment]
I am not getting requests and this error has disappeared from the logs. @daerup @crispybegs is it working for you two again as well?

**Comment by crispybegs** [comment]
it is not

<img width="774" alt="Screenshot 2024-11-02 at 16 05 40" src="https://github.com/user-attachments/assets/339fd744-1403-431c-a3ab-c312adccafa5">

**Comment by daerup** [comment]
> I am getting requests again and this error has disappeared from the logs. @daerup @crispybegs is it working for you two again as well?

Still does not work for me. I can comment if it worked previously since I haven't deployed suggestarr previously. Currently running on tag 1.0.9 (1.0.9.1 doesn't work for me...)

**Comment by crispybegs** [comment]
same here, i only installed this for the first time 2 days ago so have no idea where the problem may lie.

**Comment by darktweek** [comment]
I have the same. Ho resolve this ?

**Comment by vahtos** [comment]
Requests are still working for me as of 11 hours ago. Can you all try the latest nightly tag and see if that fixes it for you?

**Comment by crispybegs** [comment]
i just repulled the image using the 'nightly' tag then manually ran the process. that previous error seems to have disappeared, but these new ones have appeared

<img width="805" alt="Screenshot 2024-11-03 at 15 45 25" src="https://github.com/user-attachments/assets/685b9ceb-4bc8-4953-b8f6-d8c0cf415281">
<img width="858" alt="Screenshot 2024-11-03 at 15 45 41" src="https://github.com/user-attachments/assets/d557b79a-5b06-4977-81e4-963fedc57333">

in addition, i now see this:

<img width="686" alt="Screenshot 2024-11-03 at 15 47 38" src="https://github.com/user-attachments/assets/f1c6e108-058e-4d38-b867-b101f0ae904e">

..however i use plex and overseerr, not jellyfin or jellyseer, so not sure what that means in this case.

regardless, nothing seems to have been actioned from this manual run.

I must confess I'm unclear on how the process works when using plex & overseer. I was hoping some suggestions would appear.. somewhere... that I can then manually approve or decline, but I don't see any anywhere and the docs aren't exactly clear on what this would look like or how i would configure this, since there are no obvious options in the initial config.

Speaking of initial config, i just hit 'reset config' to go through it again and see if I've missed anything that might be applicable here, but the config process gets to this step and there's no obvious way to progress any further

<img width="809" alt="Screenshot 2024-11-03 at 15 50 50" src="https://github.com/user-attachments/assets/b0e964af-5d8d-4c39-bbf1-ef83bdc311b8">

**Comment by crispybegs** [comment]
yes in fact suggestarr is now no longer working as the set up process is broken.
you get to this section

<img width="757" alt="Screenshot 2024-11-03 at 15 54 39" src="https://github.com/user-attachments/assets/e0180452-0218-4e4f-8290-325055c78081">

log in with plex

<img width="583" alt="Screenshot 2024-11-03 at 15 54 48" src="https://github.com/user-attachments/assets/09900146-2a78-4dc6-9ab8-71a6d023696f">

and closing that window removes the 'next' button form the set up process, leaving you here with no way to progress

<img width="817" alt="Screenshot 2024-11-03 at 15 54 53" src="https://github.com/user-attachments/assets/e9c00c1c-e9ea-49d2-b4b5-7639a4633ff9">

so... stuck and non-functional at this point

**Comment by giuseppe99barchetta** [comment]
Hi! Tomorrow I'll check better and finally push a fix!

**Comment by crispybegs** [comment]
> Hi! Tomorrow I'll check better and finally push a fix!

grazie!

**Comment by giuseppe99barchetta** [comment]
> > Hi! Tomorrow I'll check better and finally push a fix!
> 
> grazie!

Hi! Thank you so much for your support (grazie mille, davvero! È un piccolo progetto che sta crescendo molto velocemente)! Could you try using the latest nightly tag and let me know if any of the previous errors have been resolved?

**Comment by crispybegs** [comment]
ok, i just restarted the container and it accepted my api key this time, but when it got to step three i still get this and can go no further:

<img width="815" alt="Screenshot 2024-11-04 at 09 25 49" src="https://github.com/user-attachments/assets/10a48c2d-6bb2-4bba-ae1b-a4828dc3d388">

**Comment by giuseppe99barchetta** [comment]
> ok, i just restarted the container and it accepted my api key this time, but when it got to step three i still get this and can go no further:
> 
> <img alt="Screenshot 2024-11-04 at 09 25 49" width="815" src="https://private-user-images.githubusercontent.com/129169122/382703344-10a48c2d-6bb2-4bba-ae1b-a4828dc3d388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTI3NDYsIm5iZiI6MTczMDcxMjQ0NiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzAzMzQ0LTEwYTQ4YzJkLTZiYjItNGJiYS1hZTFiLWE0ODI4ZGMzZDM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwOTI3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmM0ODg1YmRiNGMzMzRkODc5OWJkOTI5NzRjMTk2NjM5OWQyYWVmNzEzODU4ZWYzZDRmOWQ2OWMxNjViM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ekrsRYm86miH_p1QwBv5OttvP39RutSu5YEVW3TULRY">

That's strange. I can't seem to replicate the issue. Are you able to log in to Plex correctly, and does it then remove all the buttons afterward? Could you share the browser logs?

**Comment by crispybegs** [comment]
> > ok, i just restarted the container and it accepted my api key this time, but when it got to step three i still get this and can go no further:
> > <img alt="Screenshot 2024-11-04 at 09 25 49" width="815" src="https://private-user-images.githubusercontent.com/129169122/382703344-10a48c2d-6bb2-4bba-ae1b-a4828dc3d388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTI3NDYsIm5iZiI6MTczMDcxMjQ0NiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzAzMzQ0LTEwYTQ4YzJkLTZiYjItNGJiYS1hZTFiLWE0ODI4ZGMzZDM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwOTI3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmM0ODg1YmRiNGMzMzRkODc5OWJkOTI5NzRjMTk2NjM5OWQyYWVmNzEzODU4ZWYzZDRmOWQ2OWMxNjViM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ekrsRYm86miH_p1QwBv5OttvP39RutSu5YEVW3TULRY">
> 
> That's strange. I can't seem to replicate the issue. Are you able to log in to Plex correctly, and does it then remove all the buttons afterward? Could you share the browser logs?

Yes exactly, I click to log in to plex, a new window pops up and I log in to plex in that window. I get a successful log in message and am told i can now close that window, and then the step 3 suggestarr window removes all the buttons. I've tried it on two different machines (both MacOS big sur using chrome) and it's the same in each place

**Comment by giuseppe99barchetta** [comment]
> > > ok, i just restarted the container and it accepted my api key this time, but when it got to step three i still get this and can go no further:
> > > <img alt="Screenshot 2024-11-04 at 09 25 49" width="815" src="https://private-user-images.githubusercontent.com/129169122/382703344-10a48c2d-6bb2-4bba-ae1b-a4828dc3d388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTI3NDYsIm5iZiI6MTczMDcxMjQ0NiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzAzMzQ0LTEwYTQ4YzJkLTZiYjItNGJiYS1hZTFiLWE0ODI4ZGMzZDM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwOTI3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmM0ODg1YmRiNGMzMzRkODc5OWJkOTI5NzRjMTk2NjM5OWQyYWVmNzEzODU4ZWYzZDRmOWQ2OWMxNjViM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ekrsRYm86miH_p1QwBv5OttvP39RutSu5YEVW3TULRY">
> > 
> > 
> > That's strange. I can't seem to replicate the issue. Are you able to log in to Plex correctly, and does it then remove all the buttons afterward? Could you share the browser logs?
> 
> Yes exactly, I click to log in to plex, a new window pops up and I log in to plex in that window. I get a successful log in message and am told i can now close that window, and then the step 3 suggestarr window removes all the buttons. I've tried it on two different machines (both MacOS big sur using chrome) and it's the same in each place

Could you please attach the browser logs and the browser network requests?

**Comment by crispybegs** [comment]
> > > > ok, i just restarted the container and it accepted my api key this time, but when it got to step three i still get this and can go no further:
> > > > <img alt="Screenshot 2024-11-04 at 09 25 49" width="815" src="https://private-user-images.githubusercontent.com/129169122/382703344-10a48c2d-6bb2-4bba-ae1b-a4828dc3d388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTI3NDYsIm5iZiI6MTczMDcxMjQ0NiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzAzMzQ0LTEwYTQ4YzJkLTZiYjItNGJiYS1hZTFiLWE0ODI4ZGMzZDM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwOTI3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmM0ODg1YmRiNGMzMzRkODc5OWJkOTI5NzRjMTk2NjM5OWQyYWVmNzEzODU4ZWYzZDRmOWQ2OWMxNjViM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ekrsRYm86miH_p1QwBv5OttvP39RutSu5YEVW3TULRY">
> > > 
> > > 
> > > That's strange. I can't seem to replicate the issue. Are you able to log in to Plex correctly, and does it then remove all the buttons afterward? Could you share the browser logs?
> > 
> > 
> > Yes exactly, I click to log in to plex, a new window pops up and I log in to plex in that window. I get a successful log in message and am told i can now close that window, and then the step 3 suggestarr window removes all the buttons. I've tried it on two different machines (both MacOS big sur using chrome) and it's the same in each place
> 
> Could you please attach the browser logs and the browser network requests?

Sorry . I'm unsure where to get those. If you can tell me then I'll provide

**Comment by giuseppe99barchetta** [comment]
> > > > > ok, i just restarted the container and it accepted my api key this time, but when it got to step three i still get this and can go no further:
> > > > > <img alt="Screenshot 2024-11-04 at 09 25 49" width="815" src="https://private-user-images.githubusercontent.com/129169122/382703344-10a48c2d-6bb2-4bba-ae1b-a4828dc3d388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTI3NDYsIm5iZiI6MTczMDcxMjQ0NiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzAzMzQ0LTEwYTQ4YzJkLTZiYjItNGJiYS1hZTFiLWE0ODI4ZGMzZDM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwOTI3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmM0ODg1YmRiNGMzMzRkODc5OWJkOTI5NzRjMTk2NjM5OWQyYWVmNzEzODU4ZWYzZDRmOWQ2OWMxNjViM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ekrsRYm86miH_p1QwBv5OttvP39RutSu5YEVW3TULRY">
> > > > 
> > > > 
> > > > That's strange. I can't seem to replicate the issue. Are you able to log in to Plex correctly, and does it then remove all the buttons afterward? Could you share the browser logs?
> > > 
> > > 
> > > Yes exactly, I click to log in to plex, a new window pops up and I log in to plex in that window. I get a successful log in message and am told i can now close that window, and then the step 3 suggestarr window removes all the buttons. I've tried it on two different machines (both MacOS big sur using chrome) and it's the same in each place
> > 
> > 
> > Could you please attach the browser logs and the browser network requests?
> 
> Sorry . I'm unsure where to get those. If you can tell me then I'll provide

Before clicking the "Login to Plex" button in SuggestArr, press F12 in Chrome to open the Developer Tools. Keep the Developer Tools open while you go through the login process. Once the buttons disappear, please take screenshots of both the Network and Console tabs in the Developer Tools and attach them here. Thank you!

**Comment by crispybegs** [comment]
ok weird, i just tried it again and it got all the way through to setting up a local user on overserr this time, but when I hit 'back' to return to the step before this the same thing happened (buttons on step 3 disappearing) and I was stuck again.

here are the logs (with api key redacted)

<img width="1107" alt="Screenshot 2024-11-04 at 10 07 16" src="https://github.com/user-attachments/assets/926ba69e-932e-4357-8b9f-8e30fae59c19">

<img width="1112" alt="Screenshot 2024-11-04 at 10 09 01" src="https://github.com/user-attachments/assets/d44b3d7f-dd98-46e5-9b6c-bcfaa0696516">

**Comment by giuseppe99barchetta** [comment]
> ok weird, i just tried it again and it got all the way through to setting up a local user on overserr this time, but when I hit 'back' to return to the step before this the same thing happened (buttons on step 3 disappearing) and I was stuck again.
> 
> here are the logs (with api key redacted)
> 
> <img alt="Screenshot 2024-11-04 at 10 07 16" width="1107" src="https://private-user-images.githubusercontent.com/129169122/382716583-926ba69e-932e-4357-8b9f-8e30fae59c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTU5NzUsIm5iZiI6MTczMDcxNTY3NSwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzE2NTgzLTkyNmJhNjllLTkzMmUtNDM1Ny04YjlmLThlMzBmYWU1OWMxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDIxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTMyMjY2OTg4NjQxOGNiNjcxYjA4ODQ0ZTFjZDUwMTcxNDk4MTdhOTgzMzRmYzM5N2RmNjdjMGY1ZmEzOWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yU8Bdvfd1GwlJr_yoRhsh3dJz3J_t53gxTaA4pp9o9w"> <img alt="Screenshot 2024-11-04 at 10 09 01" width="1112" src="https://private-user-images.githubusercontent.com/129169122/382716679-d44b3d7f-dd98-46e5-9b6c-bcfaa0696516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTU5NzUsIm5iZiI6MTczMDcxNTY3NSwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzE2Njc5LWQ0NGIzZDdmLWRkOTgtNDZlNS05YjZjLWJjZmFhMDY5NjUxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDIxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTc4MzMzYWJjOTczOThiMTE0NDBiZDMyODZiMDY1NTVlMzc0NThlZWRmMDFkMmY3ZjhhNWQ3YTE5NTJiNzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3OreNjUNc2mageGBDPTvGkjMQq01_opc4h0mrCUUVvA">

The issue might be due to the Plex servers not being retrieved via the API. I’ve pushed a fix in `nightly` tag that allows manual entry of the Plex server URL in this case. Could you check if this resolves the problem? Thanks!

**Comment by giuseppe99barchetta** [comment]
> repulled the nightly image and tried again, but stuck here again
> 
> <img alt="Screenshot 2024-11-04 at 10 37 24" width="1718" src="https://private-user-images.githubusercontent.com/129169122/382723739-ae38acd6-f96e-4a8f-9a11-e39709aa6859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTY5OTEsIm5iZiI6MTczMDcxNjY5MSwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzIzNzM5LWFlMzhhY2Q2LWY5NmUtNGE4Zi05YTExLWUzOTcwOWFhNjg1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDkyZjM0NzcwMTI1NzM1OTAwNmVjNzJlZTQ5OGNiZGE2NjM0MTUyNWQ5OGUxYzNlYWJmMWQ0NDRkOWJlOGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cBKFTUbjqeRdOlg85ak9FeehLa7_1R1o9IoCr_V2YBE">

Same errors in the browser console? Have you restarted the container?

**Comment by crispybegs** [comment]
ok, restarting the container worked!

However I can't seem to get it to actually request any media and we're back to the original error that started this thread.

My config is:

<img width="809" alt="Screenshot 2024-11-04 at 11 15 22" src="https://github.com/user-attachments/assets/98e45491-899f-4a48-8892-4b606574ab93">

but i get:

<img width="1208" alt="Screenshot 2024-11-04 at 11 16 12" src="https://github.com/user-attachments/assets/03871914-7345-4946-bfe1-a523cb11624c">

**Comment by crispybegs** [comment]
also worth noting that to change the TMDB thresholds you have to go through the whole set up process again _but_, unless you fully restart the container, then suggestarr holds on to whatever you previously entered. That's why you can see '10' in my config but items being rejected at '20' in the logs. '20' was my previous threshold setting.

**Comment by giuseppe99barchetta** [comment]
> also worth noting that to change the TMDB thresholds you have to go through the whole set up process again _but_, unless you fully restart the container, then suggestarr holds on to whatever you previously entered. That's why you can see '10' in my config but items being rejected at '20' in the logs. '20' was my previous threshold setting and suggestarr is still using that instead of my specified '10'.

Are you using different agents for your libraries, or are all libraries set to use TheMovieDatabase agent? Could you share the configuration details for each library in Plex? Sorry for all the questions, but I need this information to help troubleshoot and apply a fix, as I'm unable to replicate the issue on my end. Thank you!

**Comment by crispybegs** [comment]
i've never really understood agents in plex tbh, but this is what's in my current agent tabs for movies. I set local assets to be preferred ages ago to stop plex overwriting my poster choices with bad ones from other sources.

<img width="995" alt="Screenshot 2024-11-04 at 12 53 43" src="https://github.com/user-attachments/assets/9e254a1f-dfdc-424f-a907-4065f5ead13d">
<img width="954" alt="Screenshot 2024-11-04 at 12 53 48" src="https://github.com/user-attachments/assets/d8a5034a-2a48-4b39-9168-498bd85f1930">
<img width="1040" alt="Screenshot 2024-11-04 at 12 53 52" src="https://github.com/user-attachments/assets/e87ce91d-dee4-493b-b7ec-a208fa6cb745">
<img width="956" alt="Screenshot 2024-11-04 at 12 53 58" src="https://github.com/user-attachments/assets/76352e11-890c-417f-b385-fb80a60648c0">

**Comment by giuseppe99barchetta** [comment]
> i've never really understood agents in plex tbh, but this is what's in my current agent tabs for movies. I set local assets to be preferred ages ago to stop plex overwriting my poster choices with bad ones from other sources.
> 
> <img alt="Screenshot 2024-11-04 at 12 53 43" width="995" src="https://private-user-images.githubusercontent.com/129169122/382760961-9e254a1f-dfdc-424f-a907-4065f5ead13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjUyOTIsIm5iZiI6MTczMDcyNDk5MiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzYwOTYxLTllMjU0YTFmLWRmZGMtNDI0Zi1hOTA3LTQwNjVmNWVhZDEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMjU2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjdhMGI2MTU5ZWUwMzYxYTlkMGI0MTMwMmI3YjMwZTIzNWRjZThiNWU2NGVjYzJkOTNkNDUxZDRkMTMyODE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gm1BkUSLKXZQpbLkgigRk1K6swusoufdf3fGQRT8ZTU"> <img alt="Screenshot 2024-11-04 at 12 53 48" width="954" src="https://private-user-images.githubusercontent.com/129169122/382760970-d8a5034a-2a48-4b39-9168-498bd85f1930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjUyOTIsIm5iZiI6MTczMDcyNDk5MiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzYwOTcwLWQ4YTUwMzRhLTJhNDgtNGIzOS05MTY4LTQ5OGJkODVmMTkzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMjU2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmNmZWYzOTMyM2JmMDg5NjFiYTQ1NWZjMzIwOWRmMTQ4NDBmYWFkODU1NDI4NDljNjk1NTI4MDViNTUwYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JEoH3L93kdZVh6xqmGAEtIkHQqssP5FarelRCuK18v4"> <img alt="Screenshot 2024-11-04 at 12 53 52" width="1040" src="https://private-user-images.githubusercontent.com/129169122/382760975-e87ce91d-dee4-493b-b7ec-a208fa6cb745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjUyOTIsIm5iZiI6MTczMDcyNDk5MiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzYwOTc1LWU4N2NlOTFkLWRlZTQtNDkzYi1iN2VjLWEyMDhmYTZjYjc0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMjU2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODRlMThlNTU5ZTIwZDQ3YjQ5MjJiNTgyMGFhMjQzM2E5ZTcxNDU3OTE2MzVjZjE2ODQyOTU0YjQ5ZTgxODM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kh-J3lbnwxL0sblKNu5Duk1HSDOQSUH6TaoED7pmHvA"> <img alt="Screenshot 2024-11-04 at 12 53 58" width="956" src="https://private-user-images.githubusercontent.com/129169122/382760979-76352e11-890c-417f-b385-fb80a60648c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjUyOTIsIm5iZiI6MTczMDcyNDk5MiwicGF0aCI6Ii8xMjkxNjkxMjIvMzgyNzYwOTc5LTc2MzUyZTExLTg5MGMtNDE3Zi1iMzg1LWZiODBhNjA2NDhjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMjU2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjk3ZjUwZmQ5MTc5OWRkM2U3MmY1NDdkNWZhYzZjZjNiNGI1ZGI5MTdjNzNlNzRhZGI1Y2Q3OWU4NGY5ZDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y7TNLK-EYHOdrMleOJPlmRWPZU3q_SJKAhg0xZjp_zw">

It seems the main issue is that you're not using The Movie Database as the movie agent to fetch metadata. The agent scanner retrieves all the necessary information for your media, such as cover images, descriptions, and other metadata. If you have time, you might try using the latest nightly version and check the log row specific to metadata in SuggestArr (like the log message pasted in the previous reply). This is likely the root cause of the error.

**Comment by crispybegs** [comment]
ah ok, that's a shame, i was hoping to be able to use this!

**Comment by giuseppe99barchetta** [comment]
Hi @vahtos, that could be the issue. If you’re able to identify which content isn’t being checked, could you open the corresponding XML file and share it here? That way, I can verify if the TMDB ID is missing in the XML.

To open the XML for the movie/show in question, click on the three dots and select "View XML."

**Comment by vahtos** [comment]
I'm not sure what it was trying to request, because the error does not include the show/movie name. From reviewing the logs:

- It is successfully identifying recently watched items, and the correct number of them
- It is excluding correctly based on my threshold value, minimum vote requirement, release year.
- It is correctly identifying previous requests and skipping them

Things only seem to go wrong when it tries to make new requests; it fails with the "Error while processing item: 'tmdb_id'" error. You'd know better than I would, but if the issue was the Plex agent, wouldn't it fail sooner than that? It's managing to identify similar content from what was watched, it just fails at the last step of making the actual requests in Overseerr.

**Comment by giuseppe99barchetta** [comment]
> I'm not sure what it was trying to request, because the error does not include the show/movie name. From reviewing the logs:
> 
> 
> 
> - It is successfully identifying recently watched items, and the correct number of them
> 
> - It is excluding correctly based on my threshold value, minimum vote requirement, release year.
> 
> - It is correctly identifying previous requests and skipping them
> 
> 
> 
> Things only seem to go wrong when it tries to make new requests; it fails with the "Error while processing item: 'tmdb_id'" error. You'd know better than I would, but if the issue was the Plex agent, wouldn't it fail sooner than that? It's managing to identify similar content from what was watched, it just fails at the last step of making the actual requests in Overseerr.
> 
> 
> 
> EDIT: I should note this is on [v1.0.14](https://github.com/giuseppe99barchetta/SuggestArr/releases/tag/v1.0.14)

No, it fails after extracting all content from Plex. When searching for similar content within the content object, it can’t find the TMDB ID. Currently, this issue should be fixed in the nightly version, but there’s another related error still present

**Comment by vahtos** [comment]
I checked all of the recently watched items it pulled from Plex. They all have TMDB IDs like this in the XML:

```
<Guid id="tmdb://1234567"/>
```

**Comment by giuseppe99barchetta** [comment]
> I checked all of the recently watched items it pulled from Plex. They all have TMDB IDs like this in the XML:
> 
> ```
> <Guid id="tmdb://1234567"/>
> ```

I've released an update in the latest version that should potentially fix this error. However, I’m not entirely sure, as I haven’t been able to identify the root cause or replicate the issue on my end.

**Comment by vahtos** [comment]
I just pulled tag v1.0.15 and reran, still having this issue. Relevant portions of logs:

```
2024-11-05 14:47:58,504 - PlexClient - ERROR - Failed to retrieve metadata for item /library/metadata/25433: 200
2024-11-05 14:47:58,554 - PlexClient - ERROR - Failed to retrieve metadata for item /library/metadata/26185: 200
2024-11-05 14:48:02,349 - PlexClient - INFO - Retrieved 278 items in tv with TMDB IDs
2024-11-05 14:48:02,453 - PlexClient - ERROR - Failed to retrieve metadata for item /library/metadata/26072: 200
2024-11-05 14:48:05,753 - PlexClient - ERROR - Failed to retrieve metadata for item /library/metadata/26932: 200
2024-11-05 14:48:09,330 - PlexClient - INFO - Retrieved 481 items in movie with TMDB IDs
2024-11-05 14:48:09,331 - ContentAutomation - INFO - Fetching recently watched content from Plex
2024-11-05 14:48:09,508 - PlexClient - INFO - All users: Returning 15 filtered recent items.
2024-11-05 14:48:09,509 - PlexClient - INFO - Total filtered items across all users: 15
...
2024-11-05 14:48:10,767 - ContentAutomation - WARNING - Error while processing item: 'tmdb_id'
...
2024-11-05 14:48:11,051 - ContentAutomation - WARNING - Error while processing item: 'tmdb_id'
...
2024-11-05 14:48:11,112 - ContentAutomation - INFO - Skipping [tv, Catastrophe]: already requested or downloaded.
2024-11-05 14:48:11,113 - ContentAutomation - INFO - Skipping [tv, Rocco Schiavone]: already requested or downloaded.
2024-11-05 14:48:11,113 - ContentAutomation - INFO - Total media requested: 0
```

**Comment by daerup** [comment]
> Yes, @crispybegs, I can almost certainly confirm that the issue is due to not using The Movie Database as the agent for your libraries.

The Movie Database Agent is deprecated as far as I know. Are there any plans to make Suggestarr compatible with the new Plex Movie agent?

**Comment by giuseppe99barchetta** [comment]
> The Movie Database Agent is deprecated as far as I know. Are there any plans to make Suggestarr compatible with the new Plex Movie agent?


Absolutely! I just need some time to figure out the best way to implement it :) Apologies for any inconvenience; in some cases, it actually does work with the Plex Movie Agent.

**Comment by Korunos47** [comment]
I still have this error. Tested with latest and nightly. 
![grafik](https://github.com/user-attachments/assets/1ff3da8a-0c83-42aa-9778-49105dd6415e)

**Comment by daerup** [comment]
I do as well...
